---
packages:
  github.com/seatgeek/mailroom:
    config:
      all: true
      recursive: true
      inpackage: true
      disable-version-string: true
      dir: "{{ .InterfaceDir }}"
      filename: "mock_{{ .InterfaceName }}.go"
      mockname: "Mock{{ .InterfaceName }}"
      outpkg: "{{ .PackageName }}"
